const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const username='beta_'+Date.now();
 require('node:fs').mkdirSync('test-results',{recursive:true});
 await page.goto(process.env.HUB_BASE_URL || 'http://127.0.0.1:8000');
 await page.getByLabel('Username').fill(username);
 await page.getByLabel('Password').fill('strong-password-123');
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await page.getByRole('heading',{name:'Your first plan, in three steps.'}).waitFor();
 await page.screenshot({path:'test-results/hub-onboarding-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/hub-first-visit-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'Try sample deadlines',exact:true}).focus();
 await page.keyboard.press('Enter');
 await page.getByRole('status').filter({hasText:'3 sample deadlines added'}).waitFor();
 assert.equal(await page.locator('.task-row').count(),3);
 await page.getByRole('button',{name:'Add deadline',exact:true}).click();
 await page.getByLabel('What needs doing?').fill('My real lab assignment');
 await page.getByLabel('Course',{exact:true}).fill('CPE');
 await page.getByRole('button',{name:'Save deadline',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Save your study hours',exact:true}).click();
 await page.getByLabel('Study from').selectOption('18');
 await page.getByLabel('Until').selectOption('22');
 await page.getByLabel('Daily minutes').fill('90');
 await page.getByRole('button',{name:'Save preferences & update plan',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Study preferences saved'}).waitFor();
 await page.waitForFunction(async()=>{const p=await fetch('/api/preferences').then(r=>r.json());return p.plan_seen===true});
 await page.reload();
 await page.getByRole('heading',{name:'You’re ready to plan your week.'}).waitFor();
 await page.getByRole('button',{name:'Weekly plan',exact:true}).click();
 assert.equal(await page.getByLabel('Study from').inputValue(),'18');
 assert.equal(await page.getByLabel('Daily minutes').inputValue(),'90');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/hub-plan-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.screenshot({path:'test-results/hub-onboarding-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Remove sample deadlines',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Sample deadlines removed'}).waitFor();
 assert.equal(await page.locator('.task-row').count(),1);
 await page.getByText('My real lab assignment',{exact:true}).first().waitFor();
 await page.getByRole('button',{name:'Sign out on mobile',exact:true}).click();
 await page.getByLabel('Username').fill(username+'_other');
 await page.getByLabel('Password').fill('strong-password-123');
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await page.getByRole('heading',{name:'Your first plan, in three steps.'}).waitFor();
 assert.equal(await page.locator('.task-row').count(),0);
 await page.getByRole('button',{name:'Weekly plan',exact:true}).click();
 assert.equal(await page.getByLabel('Daily minutes').inputValue(),'120');
 await page.getByRole('button',{name:'Imports',exact:true}).click();
 await page.getByLabel('Choose syllabus file').setInputFiles({name:'syllabus.txt',mimeType:'text/plain',buffer:Buffer.from('Lab report - 2030-01-02')});
 await page.getByRole('button',{name:'Preview import',exact:true}).click();
 await page.getByRole('heading',{name:'Review your import',exact:true}).waitFor();
 await page.getByRole('button',{name:'Confirm import',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Import complete: 1 added'}).waitFor();
 await page.getByRole('button',{name:'Deadlines',exact:false}).first().click();
 await page.getByRole('button',{name:/^Complete /}).click();
 await page.getByLabel('Deadline status').selectOption('done');
 await page.locator('.task-row.completed').waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: onboarding, samples, real-task preservation, saved preferences after refresh, account isolation, 390px layout; no browser exceptions.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
