const {chromium}=require('playwright');
const {PDFDocument}=require('pdf-lib');
const {zipSync,strToU8}=require('fflate');
const assert=require('node:assert/strict');
const fs=require('node:fs');
let studyPage;
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 const page=await context.newPage();studyPage=page;page.setDefaultTimeout(30000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const nav=async name=>page.locator('nav').getByRole('button',{name,exact:true}).click();
 await page.goto('http://127.0.0.1:8000');
 await page.getByLabel('Username').fill('study_'+Date.now());await page.getByLabel('Password').fill('strong-password-123');
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await page.getByRole('button',{name:'Enable offline access',exact:true}).click();
 await page.getByText('Online · Offline access enabled',{exact:true}).waitFor({timeout:120000});
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await nav('Materials');
 const pdf=await PDFDocument.create();pdf.addPage([450,600]).drawText('Circuits review notes',{x:40,y:530,size:22});
 const ppt=zipSync({'ppt/slides/slide1.xml':strToU8('<p:sld xmlns:p="p" xmlns:a="a"><a:p><a:r><a:t>Voltage and current</a:t></a:r></a:p></p:sld>')});
 await page.getByLabel('Add study materials',{exact:true}).setInputFiles([{name:'circuits.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())},{name:'lecture.pptx',mimeType:'application/vnd.openxmlformats-officedocument.presentationml.presentation',buffer:Buffer.from(ppt)}]);
 await page.locator('.material-card').filter({hasText:'lecture.pptx'}).click();await page.getByText('Slide 1\nVoltage and current',{exact:true}).waitFor();
 await page.locator('.material-card').filter({hasText:'circuits.pdf'}).click();await page.getByText('PDF ready · annotations saved on device',{exact:true}).waitFor();
 await page.getByLabel('PDF tool',{exact:true}).selectOption('highlight');
 await page.locator('.pdf-stage').scrollIntoViewIfNeeded();
 const box=await page.locator('.pdf-overlay').boundingBox();
 await page.mouse.move(box.x+box.width*.08,box.y+box.height*.08);await page.mouse.down();await page.mouse.move(box.x+box.width*.8,box.y+box.height*.14,{steps:8});await page.mouse.up();
 await page.getByRole('button',{name:'Undo annotation',exact:true}).waitFor();
 await page.waitForFunction(()=>document.querySelectorAll('.pdf-overlay rect').length===1);
 await page.getByLabel('Review notes',{exact:true}).fill('Review Ohm’s law before the quiz.');await page.getByRole('button',{name:'Save material notes',exact:true}).click();
 await page.getByText('Notes saved on device',{exact:true}).waitFor();
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Download annotated PDF',exact:true}).click();const exported=await downloading;assert.match(exported.suggestedFilename(),/-annotated.pdf$/);assert.equal((await PDFDocument.load(fs.readFileSync(await exported.path()))).getPageCount(),1);
 const backupWait=page.waitForEvent('download');await page.getByRole('button',{name:'Download materials backup',exact:true}).click();const backup=await backupWait;const backupPath=await backup.path();const saved=JSON.parse(fs.readFileSync(backupPath));assert.equal(saved.materials.length,2);assert.equal(saved.materials.find(m=>m.type==='pdf').annotations.length,1);
 await page.getByLabel('Restore materials backup',{exact:true}).setInputFiles(backupPath);await page.getByText('Backup restored as new copies on this account and device.',{exact:true}).waitFor();assert.equal(await page.locator('.material-card').count(),4);
 await nav('Focus timer');await page.getByLabel('Study minutes',{exact:true}).fill('1');await page.getByLabel('Rest minutes',{exact:true}).fill('1');await page.getByLabel('Number of cycles',{exact:true}).fill('2');await page.getByRole('button',{name:'Apply timer settings',exact:true}).click();
 await page.getByRole('button',{name:'Start timer',exact:true}).click();await page.getByRole('button',{name:'Pause timer',exact:true}).click();await page.getByRole('button',{name:'Resume timer',exact:true}).waitFor();
 await context.setOffline(true);await page.reload();await page.getByText('Offline · Offline access enabled',{exact:true}).waitFor();
 await nav('Focus timer');await page.getByRole('button',{name:'Resume timer',exact:true}).waitFor();assert.equal(await page.getByLabel('Number of cycles',{exact:true}).inputValue(),'2');
 await page.screenshot({path:'test-results/hub-timer-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Add deadline',exact:true}).click();await page.getByLabel('What needs doing?').fill('Offline circuits review');await page.getByLabel('Course',{exact:true}).fill('CPE');await page.getByRole('button',{name:'Save deadline',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByText('1 changes waiting to sync',{exact:true}).waitFor();
 await nav('Weekly plan');await page.getByLabel('Daily minutes',{exact:true}).fill('75');await page.getByRole('button',{name:'Save preferences & update plan',exact:true}).click();await page.getByText('2 changes waiting to sync',{exact:true}).waitFor();
 await nav('Materials');await page.locator('.material-card').filter({hasText:'circuits.pdf'}).first().click();await page.getByText('PDF ready · annotations saved on device',{exact:true}).waitFor();assert.equal(await page.getByLabel('Review notes',{exact:true}).inputValue(),'Review Ohm’s law before the quiz.');assert.equal(await page.locator('.pdf-overlay rect').count(),1);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/hub-materials-offline-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await context.setOffline(false);await page.getByText('All changes synced',{exact:true}).waitFor();
 const tasks=await page.evaluate(()=>fetch('/api/tasks').then(r=>r.json()));assert.equal(tasks.length,1);assert.equal(tasks[0].title,'Offline circuits review');assert.equal((await page.evaluate(()=>fetch('/api/preferences').then(r=>r.json()))).daily_minutes,75);
 // Server-side change while this device is offline must not be overwritten.
 await page.evaluate(async task=>{await fetch('/api/tasks/'+task.id,{method:'PUT',headers:{'Content-Type':'application/json','X-Requested-With':'StudentHub'},body:JSON.stringify({...task,title:'Changed on another device'})});},tasks[0]);
 await context.setOffline(true);await page.locator('nav').getByRole('button',{name:/Deadlines/}).click();await page.getByRole('button',{name:'Complete Offline circuits review',exact:true}).click();await page.getByText('1 changes waiting to sync',{exact:true}).waitFor();await context.setOffline(false);
 await page.getByRole('alert').filter({hasText:'changed on another device'}).waitFor();assert.equal((await page.evaluate(()=>fetch('/api/tasks').then(r=>r.json())))[0].done,false);
 const pendingWait=page.waitForEvent('download');await page.getByRole('button',{name:'Download pending changes backup',exact:true}).click();assert.ok(await (await pendingWait).path());
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Discard pending changes',exact:true}).click();await page.getByText('All changes synced',{exact:true}).waitFor();
 await context.setOffline(true);await page.getByRole('button',{name:'Sign out on mobile',exact:true}).click();await page.getByLabel('Username').waitFor();await page.reload();await page.getByLabel('Username').waitFor();
 await context.setOffline(false);await page.reload();await page.getByLabel('Username').waitFor();assert.equal((await page.request.get('http://127.0.0.1:8000/api/me')).status(),401);
 await page.getByLabel('Username').fill('other_'+Date.now());await page.getByLabel('Password').fill('strong-password-123');await page.getByRole('button',{name:'Create account',exact:true}).click();await nav('Materials');assert.equal(await page.locator('.material-card').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS: offline reload/edit/plan/reconnect/conflicts/logout isolation, PDF annotations/export/backup, PowerPoint text, timer persistence, 390px layout.');await browser.close();
})().catch(async e=>{console.error(e);if(studyPage){console.error(await studyPage.locator('body').innerText().catch(()=>''));await studyPage.screenshot({path:'test-results/hub-study-failure.png',fullPage:true}).catch(()=>{});}process.exit(1)});
