import React,{useEffect,useState,useRef} from 'react';
import {read,write} from './storage';
import {newTimer,advanceTimer} from './timer';
export default function FocusTimer({username,visible}){
 const [timer,setTimer]=useState(null),[error,setError]=useState(''),[sound,setSound]=useState(false);const audio=useRef(null);
 const key=username+':timer';
 useEffect(()=>{let alive=true;read('kv',key).then(t=>{if(alive)setTimer(advanceTimer(t||newTimer()));}).catch(e=>setError(e.message));return()=>{alive=false;};},[key]);
 async function save(t){try{await write('kv',key,t);setTimer(t);setError('');}catch(e){setError('Timer was not saved: '+e.message);}}
 useEffect(()=>{if(!timer||timer.status!=='running')return;const id=setInterval(()=>{const next=advanceTimer(timer);if(next.phase!==timer.phase||next.cycle!==timer.cycle||next.status!==timer.status){save(next);if(sound&&audio.current){const osc=audio.current.createOscillator(),gain=audio.current.createGain();osc.connect(gain);gain.connect(audio.current.destination);gain.gain.value=.08;osc.start();osc.stop(audio.current.currentTime+.3);}}else setTimer(next);},500);return()=>clearInterval(id);},[timer,sound]);
 if(!timer)return visible?<div className="panel study-panel">{error||'Opening your timer…'}</div>:null;
 const seconds=Math.ceil(timer.remaining/1000),display=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
 if(!visible)return timer.status==='running'?<div className="timer-mini" role="status">{timer.phase==='study'?'Focus':'Rest'} · {display} · Cycle {timer.cycle}/{timer.config.cycles}</div>:null;
 return <section className="panel study-panel focus-panel"><h2>Focus & rest timer</h2><p className="muted">Choose your rhythm. Rest happens between study cycles; the final study cycle finishes the session.</p>{error&&<p role="alert" className="late">{error}</p>}
 <form className="timer-settings" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));save(newTimer({study:+data.study,rest:+data.rest,cycles:+data.cycles}));}}>
 <label>Study minutes<input name="study" type="number" min="1" max="180" required defaultValue={timer.config.study} disabled={timer.status==='running'||timer.status==='paused'}/></label><label>Rest minutes<input name="rest" type="number" min="1" max="60" required defaultValue={timer.config.rest} disabled={timer.status==='running'||timer.status==='paused'}/></label><label>Number of cycles<input name="cycles" type="number" min="1" max="12" required defaultValue={timer.config.cycles} disabled={timer.status==='running'||timer.status==='paused'}/></label><button className="secondary" disabled={timer.status==='running'||timer.status==='paused'}>Apply timer settings</button></form>
 <div className="timer-phase">{timer.status==='complete'?'Session complete':timer.phase==='study'?'Time to focus':'Time to rest'} · Cycle {timer.cycle}/{timer.config.cycles}</div><div className="timer-clock" aria-label="Time remaining">{display}</div>
 <div className="study-actions">{timer.status==='running'?<button className="primary" onClick={()=>{const t=advanceTimer(timer);save(t.status==='complete'?t:{...t,status:'paused',endAt:null});}}>Pause timer</button>:timer.status!=='complete'&&<button className="primary" onClick={()=>save({...timer,status:'running',endAt:Date.now()+timer.remaining})}>{timer.status==='paused'?'Resume timer':'Start timer'}</button>}<button className="secondary" onClick={()=>save(newTimer(timer.config))}>Reset timer</button><label className="inline-check"><input type="checkbox" checked={sound} onChange={async e=>{setSound(e.target.checked);if(e.target.checked){try{const Audio=window.AudioContext||window.webkitAudioContext;audio.current ||= new Audio();await audio.current.resume();}catch{setSound(false);setError('Sound is unavailable in this browser. The timer still works.');}}}}/>Play a sound</label></div>
 <p className="fine">Saved on this device. Works offline and restores after refresh. If a tab is asleep or closed, the next visit catches up with the elapsed time; a sound is not guaranteed while your browser is suspended. This does not automatically mark coursework complete.</p></section>;
}
