import React,{useEffect,useState} from 'react';
import {read,write,list,remove,download,locked} from './storage';
import {allowedExtensions,extension,textPreview} from './formats';
import PdfReader from './PdfReader';
function ImagePreview({blob,name}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(blob);setUrl(u);return()=>URL.revokeObjectURL(u);},[blob]);return <img className="material-image" src={url} alt={name}/>;}
export default function Materials({username}){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[course,setCourse]=useState('General'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All courses'),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState(''),[noteDirty,setNoteDirty]=useState(false);
 const prefix=username+':material:';
 async function refresh(){setItems((await list('materials',prefix)).sort((a,b)=>b.updated-a.updated));}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[username]);
 async function save(value){return locked(async()=>{const existing=await read('materials',prefix+value.id);if(existing&&existing.revision!==value.revision)throw new Error('This file changed in another tab. Reopen it before saving.');const next={...value,revision:(value.revision||0)+1,updated:Date.now()};await write('materials',prefix+value.id,next);setSelected(next);await refresh();setStatus('Saved on this device');return next;});}
 async function upload(files){setBusy(true);setError('');try{for(const file of files){if(!allowedExtensions.includes(extension(file.name)))throw new Error('Unsupported format: '+file.name);if(file.size>25*1024*1024)throw new Error('Maximum material size is 25 MB per file.');let text='';try{text=await textPreview(file);}catch(e){text='Preview unavailable: '+e.message;}const value={id:crypto.randomUUID(),name:file.name,course:course.trim()||'General',blob:file,type:extension(file.name),text,notes:'',annotations:[],page:1,revision:1,updated:Date.now()};await write('materials',prefix+value.id,value);}await refresh();setStatus('Materials saved on this device. Enable offline access to reopen the site without internet.');}catch(e){setError(e.message+' Earlier files, if any, remain saved.');}finally{setBusy(false);}}
 function open(item){if(noteDirty&&!confirm('Leave without saving your material notes?'))return;setSelected(item);setNotes(item.notes||'');setNoteDirty(false);setStatus('');setError('');}
 async function backup(){setBusy(true);try{const all=await list('materials',prefix);if(all.reduce((n,m)=>n+m.blob.size,0)>100*1024*1024)throw new Error('Combined backup exceeds 100 MB. Download originals and notes individually.');const entries=[];for(const m of all){const buffer=new Uint8Array(await m.blob.arrayBuffer());let binary='';for(let i=0;i<buffer.length;i+=8192)binary+=String.fromCharCode(...buffer.subarray(i,i+8192));entries.push({...m,blob:undefined,bytes:btoa(binary)});}download(new Blob([JSON.stringify({version:1,materials:entries})],{type:'application/json'}),'student-hub-materials-backup.json');setStatus('Backup downloaded. Keep it private; it contains your materials and notes.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function restore(file){if(!file)return;setBusy(true);setError('');try{if(file.size>150*1024*1024)throw new Error('Backup is too large (150 MB maximum).');const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.materials)||data.materials.length>100)throw new Error('Not a supported materials backup.');for(const m of data.materials){if(typeof m.bytes!=='string'||m.bytes.length>36*1024*1024||typeof m.name!=='string'||!allowedExtensions.includes(extension(m.name)))throw new Error('Invalid backup file.');const bytes=Uint8Array.from(atob(m.bytes),c=>c.charCodeAt(0));if(bytes.length>25*1024*1024)throw new Error('Backup contains an oversized material.');const id=crypto.randomUUID();await write('materials',prefix+id,{...m,id,bytes:undefined,blob:new Blob([bytes]),name:m.name.slice(0,240),course:String(m.course||'General').slice(0,100),page:Number.isInteger(m.page)&&m.page>0?m.page:1,notes:String(m.notes||'').slice(0,100000),text:String(m.text||'').slice(0,15000000),annotations:Array.isArray(m.annotations)?m.annotations.slice(0,10000).filter(a=>a&&Number.isInteger(a.page)&&a.page>0&&(a.kind==='highlight'?Array.isArray(a.rect)&&a.rect.length===4&&a.rect.every(Number.isFinite):a.kind==='pen'&&Array.isArray(a.points)&&a.points.length<=10000&&a.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)))):[],revision:1,updated:Date.now()});}await refresh();setStatus('Backup restored as new copies on this account and device.');}catch(e){setError('Restore stopped: '+e.message);}finally{setBusy(false);}}
 const filtered=items.filter(m=>(filter==='All courses'||m.course===filter)&&`${m.name} ${m.course} ${m.text} ${m.notes}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="materials"><div className="panel study-panel"><h2>Your course materials</h2><p className="muted">PDFs, PowerPoints, Word documents, spreadsheets, text, and images—organized by course.</p><p className="device-notice">Files and annotations are saved only in this browser on this device, not uploaded to Render or Neon. Download backups before clearing browser data. Files do not yet sync across devices.</p>
 <div className="study-actions"><label>Course for new files<input maxLength="100" value={course} onChange={e=>setCourse(e.target.value)}/></label><label>Add study materials<input aria-label="Add study materials" type="file" multiple accept={allowedExtensions.map(x=>'.'+x).join(',')} disabled={busy} onChange={e=>{upload(Array.from(e.target.files));e.target.value='';}}/></label><button className="secondary" disabled={busy||!items.length} onClick={backup}>Download materials backup</button><label>Restore materials backup<input type="file" accept=".json" disabled={busy} onChange={e=>{restore(e.target.files[0]);e.target.value='';}}/></label></div><p className="fine">25 MB per file. PDF: read, highlight, draw, and export. PPTX/DOCX/XLSX: text preview, not original slide/page layout. PPT/DOC/XLS: store and download to open in a compatible app. Macros and embedded scripts are never executed.</p>
 {error&&<p role="alert" className="late">{error}</p>}{status&&<p role="status">{status}</p>}<div className="study-actions"><input aria-label="Search materials" placeholder="Search filenames, notes, or extracted text…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter materials by course" value={filter} onChange={e=>setFilter(e.target.value)}>{['All courses',...new Set(items.map(m=>m.course))].map(c=><option key={c}>{c}</option>)}</select></div>
 <div className="materials-list">{filtered.map(m=><button className={'material-card '+(selected?.id===m.id?'selected':'')} key={m.id} onClick={()=>open(m)}><span className="course">{m.course}</span><strong>{m.name}</strong><small>{m.type.toUpperCase()} · {(m.blob.size/1024/1024).toFixed(1)} MB · On this device</small></button>)}{!filtered.length&&<p className="empty">Add your readings or lecture files to start.</p>}</div></div>
 {selected&&<article className="panel study-panel"><div className="study-actions"><h2>{selected.name}</h2><button className="secondary" onClick={()=>download(selected.blob,selected.name)}>Download original</button><button className="secondary" onClick={()=>{if(confirm('Remove this device copy and its annotations? Download a backup first.'))remove('materials',prefix+selected.id).then(()=>{setSelected(null);setNoteDirty(false);refresh();}).catch(e=>setError(e.message));}}>Remove device copy</button></div>
 {selected.type==='pdf'?<PdfReader key={selected.id} material={selected} onChange={save}/>:['png','jpg','jpeg','webp'].includes(selected.type)?<ImagePreview blob={selected.blob} name={selected.name}/>:selected.text?<pre className="material-text">{selected.text}</pre>:<p className="fine">Preview is unavailable for this format. Download the original and open it in your usual app.</p>}
 <label className="material-notes">Review notes<textarea rows="7" value={notes} maxLength="100000" onChange={e=>{setNotes(e.target.value);setNoteDirty(true);}} placeholder="Write a summary, key formulas, or questions to review…"/></label><div className="study-actions"><button className="primary" disabled={!noteDirty||busy} onClick={async()=>{setBusy(true);try{await save({...selected,notes});setNoteDirty(false);}catch(e){setError(e.message);}finally{setBusy(false);}}}>Save material notes</button><button className="secondary" onClick={()=>download(new Blob([notes],{type:'text/plain;charset=utf-8'}),selected.name+'-notes.txt')}>Download notes</button><span role="status">{noteDirty?'Notes not saved yet':'Notes saved on device'}</span></div>
 </article>}</section>;
}
