import React,{useEffect,useRef,useState} from 'react';
import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import {PDFDocument,rgb} from 'pdf-lib';
import {download} from './storage';
pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;
export default function PdfReader({material,onChange}){
 const canvas=useRef(null),viewport=useRef(null),drag=useRef(null);const [doc,setDoc]=useState(null),[page,setPage]=useState(material.page||1),[tool,setTool]=useState('read'),[size,setSize]=useState({width:600,height:800}),[error,setError]=useState(''),[ready,setReady]=useState(false),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true,task,document;material.blob.arrayBuffer().then(data=>{if(!live)return;task=pdfjs.getDocument({data:new Uint8Array(data),isEvalSupported:false,cMapUrl:'/assets/pdf-cmaps/',cMapPacked:true,standardFontDataUrl:'/assets/pdf-standard_fonts/'});return task.promise;}).then(pdf=>{if(!pdf)return;document=pdf;if(live){setDoc(pdf);setPage(p=>Math.min(p,pdf.numPages));setError('');}}).catch(e=>{if(live)setError('Cannot open this PDF: '+e.message);});return()=>{live=false;if(task)task.destroy();};},[material.id]);
 useEffect(()=>{if(!doc)return;let live=true,render;setReady(false);doc.getPage(Math.min(page,doc.numPages)).then(p=>{if(!live)return;const v=p.getViewport({scale:1.3});viewport.current=v;setSize({width:v.width,height:v.height});canvas.current.width=v.width;canvas.current.height=v.height;render=p.render({canvasContext:canvas.current.getContext('2d'),viewport:v});return render.promise;}).then(()=>{if(live)setReady(true);}).catch(e=>{if(live&&e.name!=='RenderingCancelledException')setError(e.message);});return()=>{live=false;render?.cancel();};},[doc,page]);
 async function changePage(next){setBusy(true);try{await onChange({...material,page:next});setPage(next);setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function commit(annotations){setBusy(true);try{await onChange({...material,annotations,page});setError('');}catch(e){setError('Annotation was not saved: '+e.message);}finally{setBusy(false);}}
 function point(e){const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
 function start(e){if(tool==='read'||!ready||busy)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={start:point(e),points:[point(e)]};}
 function move(e){if(!drag.current)return;const p=point(e);if(tool==='pen')drag.current.points.push(p);setDraft({tool,start:drag.current.start,end:p,points:[...drag.current.points]});}
 function finish(e){if(!drag.current)return;const d=drag.current;drag.current=null;setDraft(null);const end=point(e),v=viewport.current;const pdf=p=>v.convertToPdfPoint(p[0]*v.width,p[1]*v.height);
  if(tool==='highlight'){if(Math.abs(end[0]-d.start[0])<.005||Math.abs(end[1]-d.start[1])<.005)return;const a=pdf(d.start),b=pdf(end);commit([...(material.annotations||[]),{id:crypto.randomUUID(),kind:'highlight',page,rect:[Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.abs(a[0]-b[0]),Math.abs(a[1]-b[1])]}]);}
  else {if(d.points.length<2)return;commit([...(material.annotations||[]),{id:crypto.randomUUID(),kind:'pen',page,points:d.points.map(pdf)}]);}
 }
 function annotation(a){const v=viewport.current;if(!v)return null;if(a.kind==='highlight'){const [x,y,w,h]=a.rect;const p=v.convertToViewportPoint(x,y),q=v.convertToViewportPoint(x+w,y+h);return <rect key={a.id} x={Math.min(p[0],q[0])} y={Math.min(p[1],q[1])} width={Math.abs(q[0]-p[0])} height={Math.abs(q[1]-p[1])} fill="#facc15" opacity=".38"/>;}return <polyline key={a.id} points={a.points.map(p=>v.convertToViewportPoint(...p).join(',')).join(' ')} fill="none" stroke="#2454df" strokeWidth="2"/>;}
 async function exportPdf(){setBusy(true);try{const pdf=await PDFDocument.load(await material.blob.arrayBuffer());for(const a of material.annotations||[]){const p=pdf.getPage(a.page-1);if(a.kind==='highlight'){const [x,y,width,height]=a.rect;p.drawRectangle({x,y,width,height,color:rgb(1,.85,0),opacity:.35});}else for(let i=1;i<a.points.length;i++)p.drawLine({start:{x:a.points[i-1][0],y:a.points[i-1][1]},end:{x:a.points[i][0],y:a.points[i][1]},thickness:1.5,color:rgb(.14,.33,.87)});}download(new Blob([await pdf.save()],{type:'application/pdf'}),material.name.replace(/\.pdf$/i,'')+'-annotated.pdf');}catch(e){setError('Could not export this PDF: '+e.message);}finally{setBusy(false);}}
 return <div>{error&&<p role="alert" className="late">{error}</p>}<div className="study-actions"><button className="secondary" disabled={!doc||page<=1||busy} onClick={()=>changePage(page-1)}>Previous page</button><span>Page {page} of {doc?.numPages||'…'}</span><button className="secondary" disabled={!doc||page>=doc.numPages||busy} onClick={()=>changePage(page+1)}>Next page</button><label>PDF tool<select aria-label="PDF tool" value={tool} onChange={e=>setTool(e.target.value)}><option value="read">Read / scroll</option><option value="highlight">Highlight area</option><option value="pen">Draw / write</option></select></label><button className="secondary" disabled={busy||!material.annotations?.length} onClick={()=>commit(material.annotations.slice(0,-1))}>Undo annotation</button><button className="primary" disabled={!doc||busy} onClick={exportPdf}>Download annotated PDF</button></div>
 <p className="fine">Drag over an area to highlight, or use Draw / write. Annotations save on this device. Use Read / scroll for touch scrolling. Original PDF text is unchanged. Downloads flatten your highlights and drawings into a new PDF; material notes can be downloaded separately.</p>
 <div className="pdf-stage" style={{aspectRatio:`${size.width}/${size.height}`}}><canvas ref={canvas} aria-label="PDF page"/><svg viewBox={`0 0 ${size.width} ${size.height}`} className={'pdf-overlay '+(tool==='read'?'reading':'drawing')} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={()=>{drag.current=null;setDraft(null);}}>{ready&&(material.annotations||[]).filter(a=>a.page===page).map(annotation)}{draft&&tool==='highlight'&&<rect x={Math.min(draft.start[0],draft.end[0])*size.width} y={Math.min(draft.start[1],draft.end[1])*size.height} width={Math.abs(draft.start[0]-draft.end[0])*size.width} height={Math.abs(draft.start[1]-draft.end[1])*size.height} fill="#facc15" opacity=".4"/>}{draft&&tool==='pen'&&<polyline points={draft.points.map(p=>`${p[0]*size.width},${p[1]*size.height}`).join(' ')} fill="none" stroke="#2454df" strokeWidth="2"/>}</svg></div><p className="fine" role="status">{busy?'Saving…':error?'Please check the error above':ready?'PDF ready · annotations saved on device':'Loading PDF…'}</p></div>;
}
